modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "death_punishment"
version = "1.0"
displayName = "Death Punishment"
description = '''

'''

[[dependencies.death_punishment]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.death_punishment]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
